### Vectorization

In [58]:
import numpy as np
import time as tm 

In [59]:
#Data creation routines in NumPy example

a = np.zeros(4);  
print (f"np.zeros(4) :  a = {a} , shape = {a.shape}, data type = {a.dtype}")

a = np.zeros((4,));
print (f"np.zeros((4,)) : a = {a} , shape = {a.shape} , data type = {a.dtype}")

a = np.random.random_sample(4); 
print (f"np.random.random_sample(4) : a= {a}, shape = {a.shape}, data type = {a.dtype}")

np.zeros(4) :  a = [0. 0. 0. 0.] , shape = (4,), data type = float64
np.zeros((4,)) : a = [0. 0. 0. 0.] , shape = (4,) , data type = float64
np.random.random_sample(4) : a= [0.52290133 0.70093002 0.71973833 0.61436243], shape = (4,), data type = float64


In [60]:
#numpy rouines which allocate memory and fill arrays with value but don't accept shape as input argument 
a = np.arange(4.); 
print (f"np.arange(4.) : a = {a} , a shape = {a.shape} , data type = {a.dtype}")

a=np.random.rand(4);
print(f"np.random.rand : a = {a} , a shape = {a.shape} ,  data type = {a.dtype}")

np.arange(4.) : a = [0. 1. 2. 3.] , a shape = (4,) , data type = float64
np.random.rand : a = [0.199155   0.52363862 0.84303824 0.78473921] , a shape = (4,) ,  data type = float64


In [61]:
#lets play with operations using vectors 


a = np.arange(0,10,1)
print(a)
a = np.arange(10)
print (a)

print (f"a[2].shape: {a[2].shape}  , a[2]= {a[2]} Accessing an element returns a scalar")

print (f"a[-1] {a[-1]}")

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
a[2].shape: ()  , a[2]= 2 Accessing an element returns a scalar
a[-1] 9


### Slicing 



In [62]:
a = np.arange(10)
print (a)

# access 5 consecutive elements (start : stop : step )
c =  a[2:7:1]
print (c)

# access 3 elemnts seperated by 2
c = a[2:7:2]
print (c)

#access all elemnts index 4 and above 
c = a[3:]
print (c)

#access all elemnts  below index 4
c = a[:3]
print (c)


[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]


### Single vector operation 

In [63]:
a = np.array([1,2,3,4])
print (a)

a1= np.arange(4)
print(a1)

b = -a
print (a)

b = np.sum(a)
print (b)

b = np.mean(a)
print (b)

b = a **2 
print (b)

[1 2 3 4]
[0 1 2 3]
[1 2 3 4]
10
2.5
[ 1  4  9 16]


In [64]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])

print (f"a+b = {a+b}")
c = np.array([1,2])

try:
    a+c
except Exception as e :
    print ("The error message you 'll see is :")
    print (e)



a+b = [0 0 6 8]
The error message you 'll see is :
operands could not be broadcast together with shapes (4,) (2,) 


In [65]:
# We can multiply vector by scalar

a = np.arange(5,)
print (a)
b = a*5
print (b)

[0 1 2 3 4]
[ 0  5 10 15 20]


## Vector DOt prodact 

In [66]:
#lets do it with for loop first 

def my_dot (a,b):
    """ Compute the dot prodact of two vectors 
    Args :
        a (ndarry (n,)) input vector
        b (ndarray (n,)) input vector with same dimension as a 
    Returns :
        x (scalar):
    """
    x = 0
    for i in range (a.shape[0]): #we use a.shape[0] because we need the only number not tuble 
        x = x + a[i] * b[i]
    return x

In [67]:
#test our 1-D function 

a = np.array ([1,2,3,4])
b = np.array ([-1,4,3,2])
print (f"my dot a , b=  {my_dot(a,b)}")

my dot a , b=  24


In [68]:
#make it with dot

c = np.dot(a,b)
print (f"np.dot(a,b) output is {c} and it's shape is {c.shape}")

c = np.dot(b,a) 
print (f"np.dot(b,a) output is {c} and it's shape is {c.shape}")

np.dot(a,b) output is 24 and it's shape is ()
np.dot(b,a) output is 24 and it's shape is ()


### Test speed vector vs loops

In [91]:
np.random.seed(1) #to keep the results 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

timestart = tm.time()
c = np.dot(a,b)
timeend = tm.time()
print (c)
print (f"np.dot(a,b) = {c:.4f}")
print (f"Vectorized version duration: {1000 * (timeend-timestart):.4f}ms ")

tic =tm.time()
d = my_dot(a,b)
toc= tm.time()

print(d)
print (f"output value for our dot function =  {d:.4f}")
print(f"our dot function time consumed = {1000*(toc-tic):.4f}ms  ")

print(f"the differnt time is {1000*((toc-tic)-(timeend-timestart))}ms ")


249825.02337924897
np.dot(a,b) = 249825.0234
Vectorized version duration: 0.3829ms 
249825.02337923684
output value for our dot function =  249825.0234
our dot function time consumed = 272.9671ms  
the differnt time is 272.5841999053955ms 


### trying simulate actual example 

In [96]:
x = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(x[1],w)

print (f"[x1 has shape {x[1].shape}")
print (f"w shape is {w.shape}")
print (f"c shape is {c.shape}")

[x1 has shape (1,)
w shape is (1,)
c shape is ()


In [107]:
# trying 2-d matrix

a = np.zeros((1,5))
print (f"a shape is {a.shape}, and  a is {a}")

a = np.zeros ((2,1))
print (f"a shape is {a.shape}, and a is {a} ")

a = np.random.random_sample((1,1))
print(f" a shape is {a.shape}, and a is {a}")



a shape is (1, 5), and  a is [[0. 0. 0. 0. 0.]]
a shape is (2, 1), and a is [[0.]
 [0.]] 
 a shape is (1, 1), and a is [[0.76080423]]


In [117]:
a = np.arange(6).reshape(-1,2)
print (f"{a} \na {a[2,1]} \na {a[2]}")


[[0 1]
 [2 3]
 [4 5]] 
a 5 
a [4 5]
